from __future__ import annotations

from collections import Counter
from datetime import datetime, timezone
from typing import Dict, List

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

SEVERITY_ORDER = ["Critical", "High", "Medium", "Info", "Low"]


def _normalize_severity(value: object) -> str:
    normalized = str(value or "Info").strip().title()
    if normalized == "Informational":
        return "Info"
    return normalized


def _severity_color(severity: str):
    normalized = _normalize_severity(severity)
    if normalized == "Critical":
        return colors.HexColor("#7F1D1D")
    if normalized == "High":
        return colors.HexColor("#9A3412")
    if normalized == "Medium":
        return colors.HexColor("#92400E")
    return colors.HexColor("#1F2937")


def _safe_text(value: object, fallback: str = "N/A") -> str:
    if value is None:
        return fallback
    text = str(value).strip()
    return text if text else fallback


def _draw_page_header_footer(canvas, doc):
    canvas.saveState()
    width, height = A4
    canvas.setStrokeColor(colors.HexColor("#D1D5DB"))
    canvas.setLineWidth(0.6)
    canvas.line(18 * mm, height - 18 * mm, width - 18 * mm, height - 18 * mm)
    canvas.setFont("Helvetica-Bold", 10)
    canvas.setFillColor(colors.HexColor("#111827"))
    canvas.drawString(20 * mm, height - 14 * mm, "PipeScope Security Assessment")
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.HexColor("#6B7280"))
    canvas.drawRightString(width - 20 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def generate_pdf_report(data: Dict, output_path):
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=24 * mm,
        bottomMargin=18 * mm,
    )
    styles = getSampleStyleSheet()

    styles.add(
        ParagraphStyle(
            name="ReportTitle",
            parent=styles["Title"],
            fontName="Helvetica-Bold",
            fontSize=24,
            leading=28,
            textColor=colors.HexColor("#111827"),
        )
    )
    styles.add(
        ParagraphStyle(
            name="SectionHeader",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=16,
            spaceAfter=6,
            textColor=colors.HexColor("#111827"),
        )
    )
    styles.add(
        ParagraphStyle(
            name="BodyMuted",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#374151"),
        )
    )
    styles.add(
        ParagraphStyle(
            name="SmallLabel",
            parent=styles["BodyText"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#4B5563"),
        )
    )
    styles.add(
        ParagraphStyle(
            name="SmallValue",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#111827"),
        )
    )

    story = []
    findings: List[Dict] = data.get("findings", [])
    target = _safe_text(data.get("target"))
    tool_name = _safe_text(data.get("tool"), "PipeScope")
    tool_version = _safe_text(data.get("version"), "N/A")
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    severity_counter = Counter(_normalize_severity(f.get("severity")) for f in findings)
    total_findings = len(findings)
    critical_count = severity_counter.get("Critical", 0)
    high_count = severity_counter.get("High", 0)
    medium_count = severity_counter.get("Medium", 0)
    info_count = severity_counter.get("Info", 0) + severity_counter.get("Low", 0)

    if (critical_count + high_count) > 0:
        risk_statement = "Immediate remediation is recommended for Critical and High findings."
    else:
        risk_statement = "No Critical or High findings were detected in this scan."

    story.append(Paragraph("Security Assessment Report", styles["ReportTitle"]))
    story.append(Paragraph("Generated by PipeScope", styles["BodyMuted"]))
    story.append(Spacer(1, 12))

    metadata_table = Table(
        [
            [
                Paragraph("Tool", styles["SmallLabel"]),
                Paragraph(tool_name, styles["SmallValue"]),
                Paragraph("Version", styles["SmallLabel"]),
                Paragraph(tool_version, styles["SmallValue"]),
            ],
            [
                Paragraph("Target", styles["SmallLabel"]),
                Paragraph(target, styles["SmallValue"]),
                Paragraph("Generated", styles["SmallLabel"]),
                Paragraph(generated_at, styles["SmallValue"]),
            ],
        ],
        colWidths=[26 * mm, 78 * mm, 26 * mm, 48 * mm],
    )
    metadata_table.setStyle(
        TableStyle(
            [
                ("BOX", (0, 0), (-1, -1), 0.8, colors.HexColor("#D1D5DB")),
                ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#E5E7EB")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F9FAFB")),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(metadata_table)
    story.append(Spacer(1, 14))

    story.append(Paragraph("Executive Summary", styles["SectionHeader"]))
    summary_text = (
        f"This report contains <b>{total_findings}</b> security findings identified in the scanned target. "
        f"Breakdown: Critical <b>{critical_count}</b>, High <b>{high_count}</b>, "
        f"Medium <b>{medium_count}</b>, Informational/Low <b>{info_count}</b>. "
        f"{risk_statement}"
    )
    story.append(Paragraph(summary_text, styles["BodyMuted"]))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Severity Distribution", styles["SectionHeader"]))
    severity_rows = [["Severity", "Count", "Share"]]
    for severity in SEVERITY_ORDER:
        count = severity_counter.get(severity, 0)
        if count == 0:
            continue
        share = f"{(count / total_findings) * 100:.1f}%" if total_findings else "0.0%"
        severity_rows.append([severity, str(count), share])
    if len(severity_rows) == 1:
        severity_rows.append(["Info", "0", "0.0%"])

    severity_table = Table(severity_rows, colWidths=[55 * mm, 25 * mm, 25 * mm])
    severity_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F2937")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ALIGN", (1, 0), (-1, -1), "CENTER"),
                ("BOX", (0, 0), (-1, -1), 0.8, colors.HexColor("#D1D5DB")),
                ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#E5E7EB")),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )

    for row_index in range(1, len(severity_rows)):
        row_severity = severity_rows[row_index][0]
        severity_table.setStyle(
            TableStyle(
                [
                    ("TEXTCOLOR", (0, row_index), (0, row_index), _severity_color(row_severity)),
                    (
                        "BACKGROUND",
                        (0, row_index),
                        (-1, row_index),
                        colors.HexColor("#FFFFFF") if row_index % 2 else colors.HexColor("#F9FAFB"),
                    ),
                ]
            )
        )

    story.append(severity_table)
    story.append(PageBreak())

    story.append(Paragraph("Detailed Findings", styles["SectionHeader"]))
    if not findings:
        story.append(Paragraph("No findings were detected for this scan target.", styles["BodyMuted"]))
    else:
        table_data = [["Severity", "ID", "Title", "Evidence", "Recommendation"]]
        for finding in findings:
            evidence = finding.get("evidence", {}) or {}
            evidence_text = _safe_text(evidence.get("file") or evidence.get("url"), "N/A")
            recommendation = _safe_text(finding.get("recommendation"), "Refer to control guidance.")
            table_data.append(
                [
                    Paragraph(_safe_text(finding.get("severity"), "Info"), styles["SmallValue"]),
                    Paragraph(_safe_text(finding.get("id"), "N/A"), styles["SmallValue"]),
                    Paragraph(_safe_text(finding.get("title"), "Untitled finding"), styles["SmallValue"]),
                    Paragraph(evidence_text, styles["SmallValue"]),
                    Paragraph(recommendation, styles["SmallValue"]),
                ]
            )

        findings_table = Table(
            table_data,
            repeatRows=1,
            colWidths=[22 * mm, 20 * mm, 42 * mm, 58 * mm, 32 * mm],
        )
        findings_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111827")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("ALIGN", (0, 0), (1, -1), "CENTER"),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("BOX", (0, 0), (-1, -1), 0.8, colors.HexColor("#D1D5DB")),
                    ("INNERGRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#E5E7EB")),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ]
            )
        )

        for row_index in range(1, len(table_data)):
            severity_value = _safe_text(findings[row_index - 1].get("severity"), "Info")
            findings_table.setStyle(
                TableStyle(
                    [
                        (
                            "BACKGROUND",
                            (0, row_index),
                            (-1, row_index),
                            colors.HexColor("#FFFFFF") if row_index % 2 else colors.HexColor("#F9FAFB"),
                        ),
                        ("TEXTCOLOR", (0, row_index), (0, row_index), _severity_color(severity_value)),
                    ]
                )
            )

        story.append(findings_table)

    doc.build(story, onFirstPage=_draw_page_header_footer, onLaterPages=_draw_page_header_footer)
